/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { DeceptiveVault, DeceptiveVaultInterface } from "../DeceptiveVault.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address payable",
        "name": "_attacker",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "balances",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "usePromoRoute",
        "type": "bool"
      }
    ],
    "name": "deposit",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getBalance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506040516102e93803806102e9833981016040819052602b91604f565b600180546001600160a01b0319166001600160a01b0392909216919091179055607a565b5f60208284031215605e575f5ffd5b81516001600160a01b03811681146073575f5ffd5b9392505050565b610262806100875f395ff3fe608060405260043610610033575f3560e01c806312065fe01461003757806327e235e314610065578063c57273c214610090575b5f5ffd5b348015610042575f5ffd5b50335f908152602081905260409020545b60405190815260200160405180910390f35b348015610070575f5ffd5b5061005361007f3660046101bb565b5f6020819052908152604090205481565b6100a361009e3660046101e8565b6100a5565b005b5f34116100f95760405162461bcd60e51b815260206004820152601e60248201527f4465706f736974206d7573742062652067726561746572207468616e2030000060448201526064015b60405180910390fd5b8015610195576001546040515f916001600160a01b03169034908381818185875af1925050503d805f8114610149576040519150601f19603f3d011682016040523d82523d5f602084013e61014e565b606091505b50509050806101915760405162461bcd60e51b815260206004820152600f60248201526e151c985b9cd9995c8819985a5b1959608a1b60448201526064016100f0565b5050565b335f90815260208190526040812080543492906101b3908490610207565b909155505050565b5f602082840312156101cb575f5ffd5b81356001600160a01b03811681146101e1575f5ffd5b9392505050565b5f602082840312156101f8575f5ffd5b813580151581146101e1575f5ffd5b8082018082111561022657634e487b7160e01b5f52601160045260245ffd5b9291505056fea2646970667358221220915d27ad4e3affd4e4d49f4063f13f2ae1cab2b6bedfffd061eab1edc9f5f2dc64736f6c63430008220033";

  
      type DeceptiveVaultConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: DeceptiveVaultConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class DeceptiveVault__factory extends ContractFactory {
    
      constructor(...args: DeceptiveVaultConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_attacker: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_attacker, overrides || {});
    };
    override deploy(_attacker: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_attacker, overrides || {}) as Promise<DeceptiveVault & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): DeceptiveVault__factory {
      return super.connect(runner) as DeceptiveVault__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): DeceptiveVaultInterface {
      return new Interface(_abi) as DeceptiveVaultInterface;
    }
    
    override attach(address: string | Addressable): DeceptiveVault {
      return super.attach(address) as DeceptiveVault;
    }
  static connect(address: string, runner?: ContractRunner | null): DeceptiveVault {
      return new Contract(address, _abi, runner) as unknown as DeceptiveVault;
    }
  }

  
  